/*
 * generated by Xtext
 */
package jp.toppers;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SgoilStandaloneSetup extends SgoilStandaloneSetupGenerated{

	public static void doSetup() {
		new SgoilStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

