/*
 * generated by Xtext
 */
package jp.toppers;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SgoilRuntimeModule extends jp.toppers.AbstractSgoilRuntimeModule {

}
