sudo: false
language: java
jdk:
- oraclejdk8
before_script:
- git config --global user.email "monaka@monami-ya.jp"
- git config --global user.name "Masaki Muranaka"
script:
- if [[ "x$TRAVIS_BRANCH" == "xmaster" && "x$TRAVIS_PULL_REQUEST" == "xfalse" ]]; then GOAL=deploy; else GOAL=install; fi
- echo "Goal is " $GOAL
- mvn -f parent/pom.xml clean $GOAL -DskipTests
after_success:
- git clone --depth=1 -b gh-pages https://${GH_TOKEN}@github.com/PizzaFactory/Sgoil.git gh-pages
- cd gh-pages
- if [[ "x$TRAVIS_BRANCH" == "xmaster" && "x$TRAVIS_PULL_REQUEST" == "xfalse" ]]; then mvn process-resources install; fi
