/*
 * generated by Xtext
 */
package jp.toppers.ui.contentassist

import jp.toppers.ui.contentassist.AbstractSgoilProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SgoilProposalProvider extends AbstractSgoilProposalProvider {
}
